export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_SELECTED_DATES_ARRAY = 'SET_SELECTED_DATES_ARRAY';

export const SET_NEXT_MONTH = 'SET_NEXT_MONTH';
export const SET_PREV_MONTH = 'SET_PREV_MONTH';
